name: CI Tumbleweed

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed

    steps:

    - name: Install additional packages
      run: zypper --non-interactive in --no-recommends autoconf automake dbus-1-devel docbook-xsl-stylesheets gcc-c++ gettext-runtime glibc-locale libacl-devel libboost_test-devel libboost_thread-devel libbtrfs-devel libbtrfsutil-devel libjson-c-devel libmount-devel libtool libxml2-devel libxslt make pam-devel xz

    - name: List installed packages
      run: rpm -qa | sort

    - name: Git checkout
      uses: actions/checkout@v1

    - name: Configure
      run: make -f Makefile.repo

    - name: Compile
      run: make -j 2

    - name: Install
      run: make install

    - name: Run unit tests
      run: make -j 2 check VERBOSE=1

    - name: Make package
      run: make package
